export const HER_NAME = "My Love";
export const SECRET_PWD = "ourDC2026";
export const ARRIVAL = "2026-06-22T00:00:00";
export const DEPARTURE = "2026-08-16T23:59:59";

export type Day = {
  id: string;
  date: string;
  day: string;
  type: string;
  tag: string;
  emoji: string;
  title: string;
  desc: string;
  cost: string;
  isSurprise?: boolean;
  secretNote?: string;
};

export type Week = {
  title: string;
  subtitle: string;
  days: Day[];
};

export type Trip = {
  type: string;
  when: string;
  icon: string;
  title: string;
  subtitle: string;
  items: Array<{ i: string; t: string }>;
  cost: string;
};

export type EatsSection = {
  section: string;
  items: Array<{ n: string; c: string; w: string; p: string }>;
};

export const weeks: Week[] = [
{
  title: "Week 1 · June 22–28", subtitle: "Welcome Week! 🎉",
  days: [
    { id:"d01", date:"Jun 22", day:"Mon", type:"arrival", tag:"💌 Arrival", emoji:"🛬",
      title:"She Arrives in DC!",
      desc:"The beginning of our summer together. Welcome to Washington, DC! ✨",
      isSurprise:true,
      secretNote:"Take at least a half day off work. Set up her room before she lands — fresh flowers, her fav snacks, a handwritten love letter, and a printed DC map with all your planned spots circled in red hearts. Play her favourite song when she walks in. 💌",
      cost:"~$35" },
    { id:"d02", date:"Jun 23", day:"Tue", type:"evening", tag:"🌙 Evening", emoji:"🌊",
      title:"The Wharf Waterfront + Dinner",
      desc:"A beautiful evening walk along the Potomac at The Wharf — great views, cool breezes, and amazing restaurants. Your first DC dinner together!",
      cost:"~$70" },
    { id:"d03", date:"Jun 24", day:"Wed", type:"musical", tag:"🎭 Evening", emoji:"🎭",
      title:"Kennedy Center — Free Show Night",
      desc:"Free Millennium Stage performance at 6pm every single night. Jazz, classical, world music. After the show: drinks on the terrace with Potomac views.",
      isSurprise:true,
      secretNote:"Tell her to 'dress up a little' but keep the destination secret until you arrive. The reveal is part of the surprise!",
      cost:"~$25" },
    { id:"d04", date:"Jun 25", day:"Thu", type:"evening", tag:"🌙 Evening", emoji:"🌅",
      title:"Sunset Picnic on the National Mall",
      desc:"Blanket, charcuterie, sparkling cider — watching the sun set behind the Lincoln Memorial and Washington Monument. Pure DC magic.",
      isSurprise:true,
      secretNote:"Pack everything secretly beforehand. Bring one flower to give her when you arrive at the spot.",
      cost:"~$25" },
    { id:"d05", date:"Jun 26", day:"Fri", type:"evening", tag:"🌙 Evening", emoji:"🍦",
      title:"Georgetown Dinner + Canal Stroll + Ice Cream",
      desc:"Dinner along M Street, a romantic walk along the C&O Canal, and ice cream at Thomas Sweet to finish. Georgetown at night is magical.",
      cost:"~$65" },
    { id:"d06", date:"Jun 27", day:"Sat", type:"weekend", tag:"☀️ Full Day", emoji:"🛍️",
      title:"Eastern Market + Capitol Hill Explore",
      desc:"DC's most beloved Saturday tradition. Local art, flowers, street food, and a walk through beautiful Capitol Hill — rowhouses, the Library of Congress, and Yards Park.",
      isSurprise:true,
      secretNote:"Buy her a fresh flower bouquet from the market. Let her lead and pick whatever she wants to explore.",
      cost:"~$45" },
    { id:"d07", date:"Jun 28", day:"Sun", type:"weekend", tag:"☀️ Full Day", emoji:"🌳",
      title:"National Arboretum Secret Garden Picnic",
      desc:"270 acres of hidden gardens and the iconic free-standing Capitol Columns — a beautiful green escape inside the city. One of DC's best-kept secrets.",
      isSurprise:true,
      secretNote:"Home-cooked picnic lunch! This will seriously impress her. Bring a good playlist and a comfy blanket.",
      cost:"~$25" },
  ]
},
{
  title: "Week 2 · June 29 – July 6", subtitle: "4th of July! 🎆 + Beach Day! 🏖️",
  days: [
    { id:"d08", date:"Jun 29", day:"Mon", type:"evening", tag:"🌙 Evening", emoji:"🍳",
      title:"Surprise Home Cook Night",
      desc:"A cozy evening in — cooking together, candles, your favourite playlist. Some of the best nights are the quiet ones. 🕯️",
      isSurprise:true,
      secretNote:"Stop by an international grocery on your way home (H Mart or Yes! Organic). Text her 'don't worry about dinner tonight 😊'. Set the table nicely with candles before she arrives.",
      cost:"~$35" },
    { id:"d09", date:"Jun 30", day:"Tue", type:"evening", tag:"🌙 Evening", emoji:"🏙️",
      title:"Rooftop Bar Night",
      desc:"DC skyline views with cocktails in hand. The city looks completely different from up high — and so do you. 😍",
      isSurprise:true,
      secretNote:"POV Rooftop at W Hotel (overlooks the White House + Monument) or Top of the Gate. Pre-sunset arrival for best views. Order her favourite cocktail style.",
      cost:"~$65" },
    { id:"d10", date:"Jul 1", day:"Wed", type:"camp", tag:"🌙 Evening", emoji:"🚣",
      title:"Evening Kayaking on the Potomac",
      desc:"Paddling at golden hour with the monuments in the background. Key Bridge Boathouse is open till 9pm — genuinely one of the most beautiful things you can do in DC.",
      isSurprise:true,
      secretNote:"Reveal the plan only when you're almost at the boathouse. Tell her 'wear something you can get wet 😄'.",
      cost:"~$45" },
    { id:"d11", date:"Jul 2", day:"Thu", type:"musical", tag:"🎵 Evening", emoji:"🎵",
      title:"U Street Live Jazz Night",
      desc:"America's historic jazz corridor — live music, incredible atmosphere, and a neighbourhood that tells DC's story like no other.",
      isSurprise:true,
      secretNote:"Pre-book tickets at Twins Jazz or Lincoln Theatre. Keep the destination secret until you walk through the door.",
      cost:"~$60" },
    { id:"d12", date:"Jul 3", day:"Fri", type:"evening", tag:"🌙 Evening", emoji:"🌃",
      title:"Pre-4th Rooftop Countdown Night",
      desc:"Last evening before the fireworks — drinks with a DC skyline view. Building anticipation for the big day tomorrow! 🎇",
      cost:"~$60" },
    { id:"d13", date:"Jul 4", day:"Sat", type:"holiday", tag:"⭐ Holiday!", emoji:"🎆",
      title:"4TH OF JULY — National Mall Fireworks!",
      desc:"The centrepiece of the whole summer. Arrive at the Mall by 3–4pm. Free live music all afternoon, food trucks, and then the most spectacular fireworks in America at 9:15pm over the monuments. ✨🇺🇸✨",
      isSurprise:true,
      secretNote:"SURPRISE SETUP: fairy lights, star-shaped sandwiches, sparklers, American flag theme, her fav drinks. Arrive by 3pm to get a great spot near the Reflecting Pool. Go ALL OUT — this is your centrepiece date.",
      cost:"~$60" },
    { id:"d14", date:"Jul 5", day:"Sun", type:"beach", tag:"🏖️ Beach Day!", emoji:"🏖️",
      title:"Rehoboth Beach, Delaware — Day Trip!",
      desc:"A beautiful beach day right after the fireworks! Rehoboth Beach is 2.5 hours from DC — gorgeous sandy shores, the famous Boardwalk, and incredible seafood. 🦀",
      isSurprise:true,
      secretNote:"Leave DC by 7am. Pack a surprise beach bag: sunscreen, her fav snacks, a fun beach game, a beach read. Stop at Dogfish Head Brewpub for dinner on the way back — it's literally in Rehoboth.",
      cost:"~$90" },
    { id:"d14b", date:"Jul 6", day:"Mon", type:"weekend", tag:"🛍️ Shopping", emoji:"🛍️",
      title:"Tysons Corner — Shopping Date Day!",
      desc:"Home turf! Tysons Corner Center and Tysons Galleria are right in our backyard — 300 stores across two malls. Explore Nordstrom, Bloomingdale's, Aritzia, Zara, and Sephora at Tysons I, then walk over to the Galleria for the luxury side. A full day of browsing, trying things on, and great food between stops. 🛍️✨",
      isSurprise:true,
      secretNote:"Tell her you're taking her shopping — but keep the Level99 entertainment surprise (40,000 sq ft of 50+ physical + mental challenges at Tysons Corner Center) for mid-afternoon. End the day with dinner at Agora in Tysons (Turkish-Mediterranean, mosaic lanterns — very romantic). She'll love this day.",
      cost:"~$100–150 (dinner + fun + whatever she picks 😄)" },
  ]
},
{
  title: "Week 3 · July 7–12", subtitle: "DC Wrap-Up + Chicago Stop",
  days: [
    { id:"d15", date:"Jul 7", day:"Tue", type:"evening", tag:"🌙 Evening", emoji:"😴",
      title:"Easy Recovery + Cozy Dinner In",
      desc:"After the big July 4th weekend, a slow evening. Takeout from somewhere amazing, looking back through all your beach and fireworks photos together. 📸",
      cost:"~$25" },
    { id:"d16", date:"Jul 8", day:"Wed", type:"evening", tag:"🌙 Evening", emoji:"🌊",
      title:"Yards Park + Navy Yard Evening Walk",
      desc:"Modern riverfront park near the Capitol — great for a golden-hour stroll, food trucks, and sometimes free outdoor music. Very local DC energy.",
      cost:"~$30" },
    { id:"d17", date:"Jul 9", day:"Thu", type:"musical", tag:"🎭 Evening", emoji:"🎭",
      title:"National Theatre — Broadway Show Night",
      desc:"A proper dressed-up date night at one of DC's most beautiful theatres. Dinner at Rasika beforehand. This is a full evening to remember. 🌹",
      isSurprise:true,
      secretNote:"Pre-book tickets at NationalTheatre.org — check for July touring Broadway shows. Don't tell her where you're going until you're almost there. Tell her: 'Dress beautifully tonight 🌹'.",
      cost:"~$130" },
    { id:"d18", date:"Jul 10", day:"Fri", type:"away", tag:"🚗 Road Trip", emoji:"🚗",
      title:"Leave DC",
      desc:"Road trip departure day. Leave DC and start the Midwest drive with snacks, playlists, and the car packed for the long stretch toward Chicago.",
      isSurprise:true,
      secretNote:"Pack the car the night before so the morning can stay calm. Keep the road trip playlist ready and put the best snacks within reach.",
      cost:"~$100 (gas + food)" },
    { id:"d19", date:"Jul 11", day:"Sat", type:"away", tag:"🏙️ Chicago", emoji:"🏠",
      title:"Chicago — Stay at Nadine and Marina's",
      desc:"Arrive in Chicago and stay at Nadine and Marina's place. Keep the evening easy after the long drive: dinner, catching up, and a proper night's rest.",
      isSurprise:true,
      secretNote:"Bring a small host gift or dessert for Nadine and Marina. It makes the stop feel intentional, not just practical.",
      cost:"~$60" },
    { id:"d20", date:"Jul 12", day:"Sun", type:"away", tag:"🚗 Road Trip", emoji:"🥐",
      title:"Brunch with Nay and Marina → St. Paul",
      desc:"Have brunch with Nay and Marina, then leave around 10am for St. Paul. The drive is about 6 hours, so plan for one relaxed stop and an easy arrival.",
      isSurprise:true,
      secretNote:"Keep the St. Paul arrival low-effort: groceries, bags inside, then a simple dinner and early night.",
      cost:"~$90 (gas + food)" },
  ]
},
{
  title: "Week 4 · July 13–19", subtitle: "Working from St. Paul + Grand Marais Birthday",
  days: [
    { id:"d21", date:"Jul 13", day:"Mon", type:"away", tag:"💻 St. Paul", emoji:"💻",
      title:"Work from St. Paul",
      desc:"First workday based in St. Paul. Keep the evening simple: settle in, reset the bags, and make the place feel comfortable for the week.",
      isSurprise:true,
      secretNote:"Find one small local treat or coffee spot nearby so the workweek still feels like part of the trip.",
      cost:"~$30" },
    { id:"d22", date:"Jul 14", day:"Tue", type:"away", tag:"💻 St. Paul", emoji:"☕",
      title:"Work from St. Paul",
      desc:"Remote workday from St. Paul. Coffee, focused work blocks, and an easy evening walk or dinner nearby after laptops close.",
      isSurprise:true,
      secretNote:"Quietly note a good St. Paul dinner option in case the day runs long and decisions need to be easy.",
      cost:"~$35" },
    { id:"d23", date:"Jul 15", day:"Wed", type:"away", tag:"💻 St. Paul", emoji:"💻",
      title:"Work from St. Paul",
      desc:"Midweek workday from St. Paul. Keep plans light and protect the evening for rest, laundry, or a low-key dinner.",
      cost:"~$30" },
    { id:"d24", date:"Jul 16", day:"Thu", type:"away", tag:"💻 St. Paul", emoji:"🎒",
      title:"Work from St. Paul + Pack for Grand Marais",
      desc:"Final St. Paul workday before the birthday weekend. Pack for Grand Marais, confirm the grocery list, and get ready for the Friday off-day drive.",
      isSurprise:true,
      secretNote:"Prep a small birthday-weekend bag with cozy layers, lake essentials, and anything that should not be forgotten in the morning.",
      cost:"~$25" },
    { id:"d25", date:"Jul 17", day:"Fri", type:"away", tag:"🚗 Grand Marais", emoji:"🛒",
      title:"Off Day — St. Paul → Grand Marais",
      desc:"Leave St. Paul around 10am for Grand Marais. Pick up groceries on the way, arrive on the North Shore, and check in at 4pm.",
      cost:"~$120 (gas + groceries)" },
    { id:"d26", date:"Jul 18", day:"Sat", type:"away", tag:"🎉 Birthday!", emoji:"🎉",
      title:"Grand Marais Birthday Celebration — Day 1",
      desc:"Birthday celebration in Grand Marais with the group. Lake Superior, shared meals, easy exploring, and a full day dedicated to celebrating.",
      isSurprise:true,
      secretNote:"Help coordinate one group toast or birthday moment so the day feels gathered and special.",
      cost:"~$80" },
    { id:"d27", date:"Jul 19", day:"Sun", type:"away", tag:"🎉 Birthday!", emoji:"🎉",
      title:"Grand Marais Birthday Celebration — Day 2",
      desc:"Second day of the birthday weekend in Grand Marais. Keep it flexible: slow morning, lake time, food with friends, and a relaxed final night.",
      isSurprise:true,
      secretNote:"Save one quiet moment for just the two of you away from the group, even if it is only a short walk by the water.",
      cost:"~$80" },
  ]
},
{
  title: "Week 5 · July 20–26", subtitle: "Back to St. Paul + Next Steps",
  days: [
    { id:"d28", date:"Jul 20", day:"Mon", type:"away", tag:"🚗 Road Trip", emoji:"🌲",
      title:"Check Out + Slowly Head Back to St. Paul",
      desc:"Check out at 11am, then take the slow route back toward St. Paul. No rush: stop when it feels right and let the birthday weekend wind down gently.",
      isSurprise:true,
      secretNote:"Print or save one favourite photo from Grand Marais before the workweek starts again.",
      cost:"~$70 (gas + food)" },
    { id:"d29", date:"Jul 21", day:"Tue", type:"away", tag:"💻 St. Paul", emoji:"💻",
      title:"Work from St. Paul",
      desc:"Back to work from St. Paul after Grand Marais. Keep the day practical and the evening easy.",
      cost:"~$30" },
    { id:"d30", date:"Jul 22", day:"Wed", type:"away", tag:"💻 St. Paul", emoji:"☕",
      title:"Work from St. Paul",
      desc:"Remote workday from St. Paul. Build in a simple coffee run or short walk so it does not feel like a lost travel day.",
      isSurprise:true,
      secretNote:"Have one backup dinner idea ready so the evening stays frictionless.",
      cost:"~$30" },
    { id:"d31", date:"Jul 23", day:"Thu", type:"away", tag:"💻 St. Paul", emoji:"💻",
      title:"Work from St. Paul",
      desc:"Final listed St. Paul workday. Close out the workweek logistics and make sure the next travel step is clear.",
      cost:"~$30" },
    { id:"d32", date:"Jul 24", day:"Fri", type:"away", tag:"🗓️ TBD", emoji:"🗓️",
      title:"July 24 — Plan TBD",
      desc:"Placeholder for the next step after the St. Paul work stretch. Details still need to be added.",
      isSurprise:true,
      secretNote:"Decide whether this becomes a travel day, rest day, or next-city day once the broader route is confirmed.",
      cost:"TBD" },
    { id:"d33", date:"Jul 25", day:"Sat", type:"away", tag:"🏙️ Chicago", emoji:"🎨",
      title:"Chicago — Day 2: Millennium Park + Lake",
      desc:"Millennium Park (the Bean!), the Art Institute of Chicago, and an afternoon on the Lakefront Trail. Chicago's lakefront is one of the best urban beaches in the world. 🌊",
      cost:"~$60" },
    { id:"d34", date:"Jul 26", day:"Sun", type:"away", tag:"🏙️ Chicago", emoji:"🌃",
      title:"Chicago — Day 3: Architecture + Last Night",
      desc:"Chicago Architecture River Cruise (absolutely worth it), brunch in Wicker Park, and a final evening in the city. Soaking up every last minute of Chicago. 🏗️",
      isSurprise:true,
      secretNote:"The architecture cruise is genuinely one of the best experiences in America — book it in advance. She will be blown away.",
      cost:"~$70" },
  ]
},
{
  title: "Week 6 · July 27 – August 2", subtitle: "🚗 Road Trip: St. Louis + 🎂 Wisconsin Birthday!",
  days: [
    { id:"d35", date:"Jul 27", day:"Mon", type:"away", tag:"🚗 Road Trip", emoji:"🌉",
      title:"Drive Chicago → St. Louis",
      desc:"4.5 hours south on I-55 from Chicago to St. Louis. Cross into Missouri and get your first view of the Gateway Arch on the horizon. Iconic American road trip moment. 🌉",
      cost:"~$60 (gas + food)" },
    { id:"d36", date:"Jul 28", day:"Tue", type:"away", tag:"🏙️ St. Louis", emoji:"🎡",
      title:"St. Louis — Gateway Arch + City Explore",
      desc:"The Gateway Arch National Park — ride to the top for a panoramic view of the Mississippi River. Then the City Museum (one of the most unique buildings in America) and a great dinner in the Soulard neighbourhood. 🏛️",
      isSurprise:true,
      secretNote:"The City Museum is completely insane in the best way — it's an adult jungle gym inside a 10-story building. Do NOT skip it. She will love it.",
      cost:"~$60" },
    { id:"d37", date:"Jul 29", day:"Wed", type:"away", tag:"🏙️ St. Louis", emoji:"🍺",
      title:"St. Louis — Forest Park + Local Eats",
      desc:"Forest Park (bigger than Central Park!) — the art museum, the zoo, and the stunning park itself, all free. Evening in the Delmar Loop for great food and live music. 🌳",
      cost:"~$45" },
    { id:"d38", date:"Jul 30", day:"Thu", type:"away", tag:"🏙️ St. Louis", emoji:"🌅",
      title:"St. Louis — Final Day + Mississippi Riverfront",
      desc:"Last morning in St. Louis — walk the cobblestone Laclede's Landing on the Mississippi, grab coffee, take it all in. Afternoon drive toward Wisconsin begins. 🚗",
      cost:"~$40" },
    { id:"d39", date:"Jul 31", day:"Fri", type:"away", tag:"🚗 Road Trip", emoji:"🧀",
      title:"Drive St. Louis → Wisconsin",
      desc:"About 5–6 hours north from St. Louis into Wisconsin. The landscape shifts from flat to rolling green hills. Arrive in time for dinner and the pre-birthday excitement. 🎂",
      cost:"~$70 (gas + food)" },
    { id:"d40", date:"Aug 1", day:"Sat", type:"away", tag:"✈️ Away Trip", emoji:"🎂",
      title:"Wisconsin — Birthday Celebration Day 1!",
      desc:"A few days in Wisconsin for the birthday celebration — not staying the whole time, just heading over for the occasion. Great food, beautiful lakes, and good company. 🥂",
      cost:"~$100" },
    { id:"d41", date:"Aug 2", day:"Sun", type:"away", tag:"✈️ Away Trip", emoji:"🎉",
      title:"Wisconsin — Birthday Day 2 + Back to DC",
      desc:"Celebrations continue, then head back to DC. If near a lake, a morning swim before leaving.",
      isSurprise:true,
      secretNote:"Carve out 20 quiet minutes from the group just for the two of you — a walk, a coffee. She'll feel it. In group trips, those private moments matter most.",
      cost:"~$80" },
  ]
},
{
  title: "Week 7 · August 3–9", subtitle: "DC + 🗽 New York City + Broadway!",
  days: [
    { id:"d42", date:"Aug 3", day:"Mon", type:"evening", tag:"🌙 Evening", emoji:"😴",
      title:"Road Trip Complete — Recovery Day",
      desc:"Home after the big DC → Grand Marais → Minneapolis → Chicago → St. Louis → Wisconsin loop. Unpack, rest, and let it all sink in. A gentle evening walk to the National Cathedral's Bishop's Garden, then home for dinner. 💛",
      cost:"~$20" },
    { id:"d43", date:"Aug 4", day:"Tue", type:"evening", tag:"🌙 Evening", emoji:"🎨",
      title:"Hirshhorn Museum + Sculpture Garden",
      desc:"DC's modern art museum — free, bold, and fascinating. The outdoor sculpture garden is especially beautiful in summer evenings.",
      cost:"~$10" },
    { id:"d44", date:"Aug 5", day:"Wed", type:"evening", tag:"💌 Surprise", emoji:"💅",
      title:"Something Special Planned Tonight 🌟",
      desc:"Ashish has a surprise evening planned just for her. All she has to do is show up. ✨",
      isSurprise:true,
      secretNote:"SOLO SPA SURPRISE. Book her a massage or facial in advance. Leave a note that morning: 'You have an appointment at [Spa Name] at 6:30pm. You deserve this. 🌹'. Cook or order dinner for when she gets home. Have flowers on the table when she returns.",
      cost:"~$110" },
    { id:"d45", date:"Aug 6", day:"Thu", type:"evening", tag:"🌙 Evening", emoji:"🌿",
      title:"Yards Park + Food Trucks + River Walk",
      desc:"A lovely last DC Thursday — Anacostia Riverfront walk, food trucks at Yards Park, and maybe an outdoor concert. Savouring the city before our NYC escape.",
      cost:"~$30" },
    { id:"d46", date:"Aug 7", day:"Fri", type:"nyc", tag:"🗽 NYC!", emoji:"🗽",
      title:"NEW YORK CITY — We're Going to NYC!",
      desc:"Amtrak from DC Union Station — 2.5 hours and we're in Manhattan. Late-night NYC pizza, Times Square, and the energy of the city that never sleeps. 🌃",
      isSurprise:true,
      secretNote:"Take the 6pm Amtrak after work (no PTO needed). Book early for ~$60–80 each way. Check into the hotel. Walk Times Square at night — let her feel the city.",
      cost:"~$180" },
    { id:"d47", date:"Aug 8", day:"Sat", type:"nyc", tag:"🎭 BROADWAY!", emoji:"🎭",
      title:"BROADWAY SHOW + Full NYC Day! 🗽",
      desc:"Morning on the High Line and Chelsea Market. Afternoon in Central Park and Times Square. Then... BROADWAY. The real thing, in New York City, together. This is the one. 🌟",
      isSurprise:true,
      secretNote:"THE BIG ONE. Ask her once which show she's always dreamed of seeing — book THAT show. Don't reveal it until you hand her the tickets at the theatre entrance. Telecharge.com or TodayTix — book 4–6 weeks ahead. She. Will. Cry. Good tears.",
      cost:"~$200" },
    { id:"d48", date:"Aug 9", day:"Sun", type:"nyc", tag:"🗽 NYC", emoji:"🌅",
      title:"NYC Morning + Return to DC",
      desc:"Morning bagels and coffee, a walk across the Brooklyn Bridge or through the Village, then the Amtrak home. Arriving back in DC feels different after NYC — in a good way.",
      isSurprise:true,
      secretNote:"Buy her one meaningful NYC memento — a book from The Strand, a print from a street artist, something small and real.",
      cost:"~$100" },
  ]
},
{
  title: "Week 8 · August 10–16", subtitle: "Our Final Week Together 💔→💖",
  days: [
    { id:"d49", date:"Aug 10", day:"Mon", type:"evening", tag:"🌙 Evening", emoji:"📸",
      title:"Summer Photos + Memory Night",
      desc:"Looking through all our summer photos together — DC, the beach, Minnesota, Wisconsin, NYC. A whole season in pictures. 💕",
      isSurprise:true,
      secretNote:"ORDER THE PHOTO BOOK TONIGHT (Artifact Uprising or Shutterfly — allow 7 days delivery). Play music from each trip while scrolling through photos. Make her laugh, then make her cry.",
      cost:"~$60" },
    { id:"d50", date:"Aug 11", day:"Tue", type:"evening", tag:"💌 Memories", emoji:"📷",
      title:"Recreate Our Week-1 Photos",
      desc:"Revisiting 2–3 of our first spots from her arrival week and taking the same photos — side-by-side before/after. This is who we were. This is who we became. 💖",
      cost:"~$15" },
    { id:"d51", date:"Aug 12", day:"Wed", type:"evening", tag:"🌙 Evening", emoji:"🛍️",
      title:"Georgetown Souvenir Hunt",
      desc:"Walking Georgetown boutiques and bookshops for keepsakes from each adventure — a DC print, a Great Lakes piece, a Broadway poster, a Wisconsin memento. One for each journey.",
      cost:"~$60" },
    { id:"d52", date:"Aug 13", day:"Thu", type:"musical", tag:"🎭 Evening", emoji:"🎭",
      title:"Final Musical Night — The Big One",
      desc:"The last big night out. Best show available this week — dressed up, great dinner beforehand, front-section seats. Making the final Thursday unforgettable.",
      isSurprise:true,
      secretNote:"Book the best show available. Make it a full date: her favourite outfit, dinner at her favourite restaurant from the summer, the best seats you can afford. The dinner toast is about what the summer meant.",
      cost:"~$140" },
    { id:"d53", date:"Aug 14", day:"Fri", type:"evening", tag:"💌 Special", emoji:"🍽️",
      title:"Recreate Our Very First Dinner",
      desc:"Going back to the first restaurant from her arrival week. Same table if possible. A toast to everything we did, everywhere we went, every moment we shared. 🥂",
      isSurprise:true,
      secretNote:"GIVE HER THE PHOTO BOOK at dinner. Tissues will be required. Tell her one favourite memory from each of the 8 weeks. 💖",
      cost:"~$85" },
    { id:"d54", date:"Aug 15", day:"Sat", type:"weekend", tag:"☀️ Her Day", emoji:"💖",
      title:"Her Perfect Last Day — She Chooses Everything",
      desc:"Today is entirely hers. Whatever she wants to do, eat, see, or revisit — we do it. Surprise breakfast in bed in the morning, her favourite spot at sunset. No schedule. Just us.",
      isSurprise:true,
      secretNote:"Write her the goodbye letter tonight, sealed for tomorrow. Make this the most intentional day of the whole summer.",
      cost:"~$80" },
    { id:"d55", date:"Aug 16", day:"Sun", type:"arrival", tag:"✈️ Goodbye", emoji:"💌",
      title:"She Flies Home — Make It Beautiful, Not Sad",
      desc:"Slow morning. Big breakfast. One last walk to her favourite DC spot. A warm send-off at the airport — hold her tight and don't let go too quickly. Until next time. 💖",
      isSurprise:true,
      secretNote:"Slip a sealed love letter into her bag before you leave for the airport. She opens it on the plane. Talk about your favourite memories, what she means to you, and what comes next. Make it count. This is what she carries home.",
      cost:"~$20" },
  ]
}
];

export const trips: Trip[] = [
  { type:"beach",
    when:"Sunday, July 5", icon:"🏖️",
    title:"Rehoboth Beach, Delaware",
    subtitle:"Beach Day Trip — 2.5 hrs from DC",
    items:[
      {i:"🚗",t:"Leave DC by 7am — arrive by 9:30am"},
      {i:"🏄",t:"Full day at one of the East Coast's most beautiful beaches — gorgeous sand and a classic Boardwalk"},
      {i:"🦀",t:"Lunch: fresh seafood right on the Boardwalk"},
      {i:"🍺",t:"Dinner at Dogfish Head Brewpub — legendary craft beer, and it's literally IN Rehoboth"},
      {i:"🌅",t:"Drive home, back in DC by 9pm"},
    ], cost:"~$90 per couple (gas + food)" },
  { type:"mn",
    when:"July 10–24 (Midwest Road Trip)", icon:"🚗",
    title:"The Great Midwest Road Trip",
    subtitle:"DC → Chicago → St. Paul → Grand Marais → St. Paul",
    items:[
      {i:"🚗",t:"Leave DC on Friday, July 10 and head toward Chicago"},
      {i:"🏠",t:"Chicago (Jul 11): Stay at Nadine and Marina's place"},
      {i:"🥐",t:"Jul 12: Brunch with Nay and Marina, then leave around 10am for St. Paul"},
      {i:"💻",t:"St. Paul (Jul 13–16): Work remotely"},
      {i:"🌲",t:"Grand Marais (Jul 17–20): Groceries, 4pm check-in, birthday celebration, 11am checkout"},
      {i:"💻",t:"St. Paul (Jul 21–23): Work remotely"},
      {i:"🗓️",t:"Jul 24: Details TBD"},
    ], cost:"TBD (gas + food; lodging mix of friends/hosts)" },
  { type:"wi",
    when:"July 31 – August 2", icon:"🎂",
    title:"Wisconsin — Birthday Celebration",
    subtitle:"Final stop on the Midwest Road Trip",
    items:[
      {i:"🚗",t:"Arrive from St. Louis — last leg of the big road trip"},
      {i:"🎉",t:"Birthday celebration with friends"},
      {i:"🏊",t:"Wisconsin's beautiful lakes — swimming or kayaking if near the lake region"},
      {i:"🧀",t:"Wisconsin classics: cheese curds, Friday fish fry, craft beer"},
      {i:"💕",t:"Carve out private time just for the two of you among the group energy"},
      {i:"🏡",t:"Head back to DC/VA after the celebrations"},
    ], cost:"Part of the overall road trip budget" },
  { type:"nyc",
    when:"August 7–9 (Fri–Sun)", icon:"🗽",
    title:"New York City + BROADWAY",
    subtitle:"The Big One — Broadway Show! 🎭",
    items:[
      {i:"🚂",t:"Amtrak from DC Union Station — 2.5 hrs, book ahead for ~$60–80 each way"},
      {i:"🌃",t:"Fri night: Times Square, late-night NYC slice, walk Manhattan"},
      {i:"🌿",t:"Sat morning: High Line + Chelsea Market breakfast + Central Park"},
      {i:"🎭",t:"Saturday evening: BROADWAY SHOW — the whole reason for this trip!"},
      {i:"🥯",t:"Sun morning: Brooklyn bagels + Bridge walk, Amtrak home by noon"},
    ], cost:"~$500–700 per couple (Amtrak + hotel + show + food)" },
];

export const eats: EatsSection[] = [
  { section:"🌟 Special Night Out", items:[
    {n:"Rasika",c:"Modern Indian · Penn Quarter",w:"James Beard award-winning. The palak chaat alone is worth it. Book 2+ weeks ahead.",p:"$$$"},
    {n:"Tail Up Goat",c:"Creative American · Adams Morgan",w:"Inventive, romantic, the best cocktails in DC. Perfect for a special splurge.",p:"$$$"},
    {n:"The Dabney",c:"Mid-Atlantic · Shaw",w:"Farm-to-table, cozy, fireplace. Deeply romantic. Very DC.",p:"$$$"},
    {n:"Bresca",c:"French Modern · 14th St NW",w:"Stunning plating, intimate setting. One of DC's most acclaimed restaurants.",p:"$$$$"},
  ]},
  { section:"💕 Romantic Vibes", items:[
    {n:"Compass Rose",c:"Global Street Food · 14th St NW",w:"Cozy, world-travels themed, amazing khachapuri and perfect cocktails.",p:"$$"},
    {n:"Filomena",c:"Italian · Georgetown",w:"Old-school Georgetown Italian — romantic atmosphere and great pasta.",p:"$$$"},
    {n:"Old Ebbitt Grill",c:"Classic American · Downtown",w:"Historic Victorian décor, great raw bar, perfect for a DC Sunday brunch date.",p:"$$"},
  ]},
  { section:"🎉 Fun & Lively", items:[
    {n:"Jaleo",c:"Spanish Tapas · Penn Quarter",w:"José Andrés' flagship — incredible tapas, sangria, and the best energy.",p:"$$"},
    {n:"Maketto",c:"Cambodian-Taiwanese · H Street NE",w:"Trendy, multicultural, great for an H Street corridor night out.",p:"$$"},
    {n:"China Chilcano",c:"Peruvian-Japanese · Penn Quarter",w:"Unique fusion, amazing cocktails, very cool space.",p:"$$"},
  ]},
  { section:"🍔 Casual & Local", items:[
    {n:"Ben's Chili Bowl",c:"American Classic · U Street",w:"DC institution since 1958. The chili half-smoke is a must-try.",p:"$"},
    {n:"Founding Farmers",c:"Farm-to-Table · Foggy Bottom",w:"Great brunch, huge portions. Also conveniently near Kennedy Center!",p:"$$"},
    {n:"Call Your Mother Deli",c:"Jewish Deli · Capitol Hill",w:"DC's most beloved deli — incredible bagels. Perfect solo lunch spot.",p:"$"},
  ]},
  { section:"🌍 Global Flavours", items:[
    {n:"Maydan",c:"Middle Eastern · 14th St NW",w:"Dramatic wood-fire open kitchen. Bold North African and Levantine flavors. Unmissable.",p:"$$"},
    {n:"Doi Moi",c:"Southeast Asian · 14th St NW",w:"Thai and Vietnamese inspired, great cocktails, always a great time.",p:"$$"},
    {n:"Rasika West End",c:"Modern Indian · West End",w:"Sister to Rasika, steps from Kennedy Center — perfect pre-show dinner.",p:"$$$"},
  ]},
  { section:"🗺️ Northern Virginia & Tysons", items:[
    {n:"Agora",c:"Turkish-Mediterranean · Tysons",w:"Mosaic lanterns, rich mezze, and an Ottoman-inspired menu. One of the most romantic atmospheres in all of NoVA — great for a special date night close to home.",p:"$$$"},
    {n:"The Naisho Room",c:"Speakeasy · Watermark Hotel, Tysons",w:"Hidden, reservation-only speakeasy inside The Watermark Hotel. Tokyo-inspired cocktails, low lighting, very exclusive. A perfect surprise — she won't know where you're taking her until you walk in.",p:"$$$"},
    {n:"Modan",c:"Modern Japanese · Tysons",w:"Sleek Japanese restaurant in a luxury Tysons high-rise — dry-aged fish, king salmon carpaccio with truffle aioli, and polished service. Great for a special night.",p:"$$$"},
    {n:"The Palm",c:"Classic Steakhouse · Tysons Corner",w:"The iconic American steakhouse. White tablecloths, exceptional service, and food that never disappoints. A proper date-night classic right at Tysons.",p:"$$$$"},
    {n:"Founding Farmers",c:"Farm-to-Table · Fairfax",w:"A Fairfax staple — great brunch, huge portions, local and sustainable. Perfect for a slow Sunday morning close to home before heading into DC.",p:"$$"},
  ]},
  { section:"☕ Cafes & Bakeries", items:[
    {n:"Tatte Bakery & Café",c:"Café & Bakery · Dupont / Georgetown / City Center",w:"Israeli-inspired pastries with stunning interiors — perfect for a slow Saturday morning. Multiple DC locations. The tahini croissant and shakshuka are both incredible.",p:"$"},
    {n:"Baked & Wired",c:"Bakery & Coffee · Georgetown",w:"DC's most beloved cupcake shop — giant, creative flavours and great coffee. A Georgetown must. Get there early before they sell out of the best ones.",p:"$"},
    {n:"Seylou",c:"Artisan Bakery · Blagden Alley",w:"Mills its own grain in-house, bakes in a wood-fired oven. The most interesting bakery in DC, tucked into Blagden Alley — the alley itself is beautiful and worth the detour.",p:"$"},
    {n:"Pluma",c:"Café · The Wharf + Union Market",w:"Warm, sophisticated café right at The Wharf. Perfect for a slow morning before your waterfront walk — specialty coffee and beautiful pastries.",p:"$"},
    {n:"Dog Tag Bakery",c:"Café & Bakery · Georgetown",w:"A nonprofit café that trains military veterans and their families. The story alone makes it worth a visit — and the pastries and sandwiches are genuinely great.",p:"$"},
    {n:"Compass Coffee",c:"Coffee · Multiple Locations",w:"DC's own specialty coffee chain. Consistently great, always cozy, and in the best neighbourhoods. The perfect pit-stop between museums or monuments.",p:"$"},
  ]},
];
